// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReferencesRouteImport } from './routes/references'
import { Route as PathsRouteImport } from './routes/paths'
import { Route as MapRouteImport } from './routes/map'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TopicsSlugRouteImport } from './routes/topics/$slug'

const ReferencesRoute = ReferencesRouteImport.update({
  id: '/references',
  path: '/references',
  getParentRoute: () => rootRouteImport,
} as any)
const PathsRoute = PathsRouteImport.update({
  id: '/paths',
  path: '/paths',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsSlugRoute = TopicsSlugRouteImport.update({
  id: '/topics/$slug',
  path: '/topics/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/map': typeof MapRoute
  '/paths': typeof PathsRoute
  '/references': typeof ReferencesRoute
  '/topics/$slug': typeof TopicsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/map': typeof MapRoute
  '/paths': typeof PathsRoute
  '/references': typeof ReferencesRoute
  '/topics/$slug': typeof TopicsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/map': typeof MapRoute
  '/paths': typeof PathsRoute
  '/references': typeof ReferencesRoute
  '/topics/$slug': typeof TopicsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/map' | '/paths' | '/references' | '/topics/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/map' | '/paths' | '/references' | '/topics/$slug'
  id: '__root__' | '/' | '/map' | '/paths' | '/references' | '/topics/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MapRoute: typeof MapRoute
  PathsRoute: typeof PathsRoute
  ReferencesRoute: typeof ReferencesRoute
  TopicsSlugRoute: typeof TopicsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/references': {
      id: '/references'
      path: '/references'
      fullPath: '/references'
      preLoaderRoute: typeof ReferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paths': {
      id: '/paths'
      path: '/paths'
      fullPath: '/paths'
      preLoaderRoute: typeof PathsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/$slug': {
      id: '/topics/$slug'
      path: '/topics/$slug'
      fullPath: '/topics/$slug'
      preLoaderRoute: typeof TopicsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MapRoute: MapRoute,
  PathsRoute: PathsRoute,
  ReferencesRoute: ReferencesRoute,
  TopicsSlugRoute: TopicsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
